# https://taskfile.dev
version: '3'
vars:
  BINFILE: http-echo

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - go mod download
      - CGO_ENABLED=0 go build .
    # silent: true
    sources:
      - http-echo.go
      - go*
    method: checksum
    generates:
      - "{{.BINFILE}}"

  run:
    desc: "Run the binary"
    deps: 
      - build
    cmds:
      - ./{{.BINFILE}}

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean