# https://taskfile.dev
version: '3'
vars:
  BINFILE: http-echo

tasks:
  default:
    cmds:
      - go get
      - CGO_ENABLED=0 go build .
      - upx ./{{.BINFILE}}
    # silent: true
    sources:
      - http-echo.go
      - go*
    method: checksum
    generates:
      - "{{.BINFILE}}"

  run:
    deps: 
      - default
    cmds:
      - ./{{.BINFILE}}

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean